# Generated by Django 5.2.1 on 2025-05-29 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="激活状态"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模型名称")),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("text_generation", "文本生成"),
                            ("image_generation", "图像生成"),
                            ("text_to_speech", "语音合成"),
                            ("speech_to_text", "语音识别"),
                            ("translation", "翻译"),
                            ("summarization", "文本摘要"),
                            ("code_generation", "代码生成"),
                            ("chatbot", "聊天机器人"),
                            ("sentiment_analysis", "情感分析"),
                            ("object_detection", "物体检测"),
                        ],
                        max_length=50,
                        verbose_name="模型类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="模型描述")),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", max_length=20, verbose_name="版本号"
                    ),
                ),
                ("api_endpoint", models.URLField(verbose_name="API端点")),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API密钥"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("inactive", "非活跃"),
                            ("maintenance", "维护中"),
                            ("deprecated", "已弃用"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "max_requests_per_minute",
                    models.PositiveIntegerField(
                        default=60, verbose_name="每分钟最大请求数"
                    ),
                ),
                (
                    "cost_per_request",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        max_digits=10,
                        verbose_name="每次请求成本",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(blank=True, default=dict, verbose_name="配置参数"),
                ),
            ],
            options={
                "verbose_name": "AI模型",
                "verbose_name_plural": "AI模型",
                "db_table": "ai_models",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AITemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="激活状态"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("prompt", "提示模板"),
                            ("workflow", "工作流模板"),
                            ("preset", "预设模板"),
                        ],
                        max_length=20,
                        verbose_name="模板类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="模板描述")),
                ("content", models.TextField(verbose_name="模板内容")),
                ("variables", models.JSONField(default=list, verbose_name="变量定义")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="公开模板"),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, verbose_name="使用次数"),
                ),
            ],
            options={
                "verbose_name": "AI模板",
                "verbose_name_plural": "AI模板",
                "db_table": "ai_templates",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="AIUsageStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="激活状态"),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "request_count",
                    models.PositiveIntegerField(default=0, verbose_name="请求次数"),
                ),
                (
                    "token_count",
                    models.PositiveIntegerField(default=0, verbose_name="Token总数"),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        max_digits=10,
                        verbose_name="总成本",
                    ),
                ),
                (
                    "success_count",
                    models.PositiveIntegerField(default=0, verbose_name="成功次数"),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(default=0, verbose_name="错误次数"),
                ),
            ],
            options={
                "verbose_name": "AI使用统计",
                "verbose_name_plural": "AI使用统计",
                "db_table": "ai_usage_stats",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="激活状态"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="对话标题")),
                (
                    "system_prompt",
                    models.TextField(blank=True, verbose_name="系统提示"),
                ),
                ("context", models.JSONField(default=list, verbose_name="对话上下文")),
                (
                    "total_tokens",
                    models.PositiveIntegerField(default=0, verbose_name="总Token数"),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        max_digits=10,
                        verbose_name="总成本",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="已归档"),
                ),
            ],
            options={
                "verbose_name": "聊天对话",
                "verbose_name_plural": "聊天对话",
                "db_table": "ai_chat_conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="激活状态"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "用户"),
                            ("assistant", "AI助手"),
                            ("system", "系统"),
                        ],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "tokens",
                    models.PositiveIntegerField(default=0, verbose_name="Token数"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        max_digits=10,
                        verbose_name="成本",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
            ],
            options={
                "verbose_name": "聊天消息",
                "verbose_name_plural": "聊天消息",
                "db_table": "ai_chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="激活状态"),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("text", "文本请求"),
                            ("image", "图像请求"),
                            ("audio", "音频请求"),
                            ("video", "视频请求"),
                            ("file", "文件请求"),
                        ],
                        max_length=20,
                        verbose_name="请求类型",
                    ),
                ),
                ("input_data", models.JSONField(verbose_name="输入数据")),
                (
                    "output_data",
                    models.JSONField(blank=True, null=True, verbose_name="输出数据"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="处理时间(秒)"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        max_digits=10,
                        verbose_name="成本",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "ai_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="ai.aimodel",
                        verbose_name="AI模型",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI请求",
                "verbose_name_plural": "AI请求",
                "db_table": "ai_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
