# Generated by Django 5.2.1 on 2025-05-29 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="airequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="aitemplate",
            name="ai_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="ai.aimodel",
                verbose_name="适用模型",
            ),
        ),
        migrations.AddField(
            model_name="aitemplate",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_ai_templates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="aiusagestats",
            name="ai_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_stats",
                to="ai.aimodel",
                verbose_name="AI模型",
            ),
        ),
        migrations.AddField(
            model_name="aiusagestats",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_usage_stats",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="ai_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="ai.aimodel",
                verbose_name="AI模型",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_conversations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="ai.chatconversation",
                verbose_name="对话",
            ),
        ),
        migrations.AddIndex(
            model_name="airequest",
            index=models.Index(
                fields=["user", "status"], name="ai_requests_user_id_3b61d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airequest",
            index=models.Index(
                fields=["ai_model", "created_at"], name="ai_requests_ai_mode_4f8132_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aiusagestats",
            unique_together={("user", "ai_model", "date")},
        ),
    ]
