# Generated by Django 5.2.1 on 2025-05-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="密钥名称")),
                (
                    "key",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="API密钥"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="激活状态"),
                ),
                (
                    "permissions",
                    models.JSONField(blank=True, default=list, verbose_name="权限列表"),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后使用时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "API密钥",
                "verbose_name_plural": "API密钥",
                "db_table": "auth_api_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="验证令牌"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                ("is_used", models.BooleanField(default=False, verbose_name="已使用")),
            ],
            options={
                "verbose_name": "邮箱验证令牌",
                "verbose_name_plural": "邮箱验证令牌",
                "db_table": "auth_email_verification_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, verbose_name="用户名")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                ("user_agent", models.TextField(blank=True, verbose_name="用户代理")),
                (
                    "is_successful",
                    models.BooleanField(default=False, verbose_name="登录成功"),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="失败原因"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="尝试时间"),
                ),
            ],
            options={
                "verbose_name": "登录尝试",
                "verbose_name_plural": "登录尝试",
                "db_table": "auth_login_attempts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="重置令牌"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                ("is_used", models.BooleanField(default=False, verbose_name="已使用")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="请求IP"
                    ),
                ),
            ],
            options={
                "verbose_name": "密码重置令牌",
                "verbose_name_plural": "密码重置令牌",
                "db_table": "auth_password_reset_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TwoFactorAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=False, verbose_name="启用状态"),
                ),
                (
                    "secret_key",
                    models.CharField(blank=True, max_length=32, verbose_name="密钥"),
                ),
                (
                    "backup_codes",
                    models.JSONField(blank=True, default=list, verbose_name="备用代码"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "双因子认证",
                "verbose_name_plural": "双因子认证",
                "db_table": "auth_two_factor",
            },
        ),
    ]
