# Generated by Django 5.2.1 on 2025-05-29 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="激活状态"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="形象名称")),
                (
                    "avatar_type",
                    models.CharField(
                        choices=[
                            ("human", "人类"),
                            ("anime", "动漫"),
                            ("robot", "机器人"),
                            ("animal", "动物"),
                            ("fantasy", "幻想"),
                            ("custom", "自定义"),
                        ],
                        default="human",
                        max_length=20,
                        verbose_name="形象类型",
                    ),
                ),
                ("model_data", models.JSONField(default=dict, verbose_name="模型数据")),
                (
                    "appearance_data",
                    models.JSONField(default=dict, verbose_name="外观数据"),
                ),
                ("animations", models.JSONField(default=list, verbose_name="动画数据")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/thumbnails/",
                        verbose_name="缩略图",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="默认形象"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="公开形象"),
                ),
            ],
            options={
                "verbose_name": "虚拟形象",
                "verbose_name_plural": "虚拟形象",
                "db_table": "metaverse_avatars",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="激活状态"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="活动标题")),
                ("description", models.TextField(verbose_name="活动描述")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("meeting", "会议"),
                            ("party", "聚会"),
                            ("concert", "音乐会"),
                            ("exhibition", "展览"),
                            ("game", "游戏"),
                            ("education", "教育"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="活动类型",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "已安排"),
                            ("ongoing", "进行中"),
                            ("ended", "已结束"),
                            ("cancelled", "已取消"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="活动状态",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=100, verbose_name="最大参与人数"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="公开活动"),
                ),
                (
                    "registration_required",
                    models.BooleanField(default=False, verbose_name="需要注册"),
                ),
            ],
            options={
                "verbose_name": "元宇宙活动",
                "verbose_name_plural": "元宇宙活动",
                "db_table": "metaverse_events",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="EventParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="激活状态"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "已注册"),
                            ("attended", "已参加"),
                            ("cancelled", "已取消"),
                        ],
                        default="registered",
                        max_length=20,
                        verbose_name="参与状态",
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "attended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="参加时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "活动参与者",
                "verbose_name_plural": "活动参与者",
                "db_table": "metaverse_event_participants",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="激活状态"),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="会话ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connecting", "连接中"),
                            ("active", "活跃"),
                            ("idle", "空闲"),
                            ("disconnected", "已断开"),
                        ],
                        default="connecting",
                        max_length=20,
                        verbose_name="会话状态",
                    ),
                ),
                ("position", models.JSONField(default=dict, verbose_name="位置信息")),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, verbose_name="最后活跃时间"),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(default=0, verbose_name="会话时长(秒)"),
                ),
                (
                    "device_info",
                    models.JSONField(default=dict, verbose_name="设备信息"),
                ),
            ],
            options={
                "verbose_name": "用户会话",
                "verbose_name_plural": "用户会话",
                "db_table": "metaverse_user_sessions",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="VirtualObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="激活状态"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="物品名称")),
                ("description", models.TextField(blank=True, verbose_name="物品描述")),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("furniture", "家具"),
                            ("decoration", "装饰"),
                            ("interactive", "交互物品"),
                            ("vehicle", "载具"),
                            ("tool", "工具"),
                            ("game", "游戏物品"),
                            ("media", "媒体"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="物品类型",
                    ),
                ),
                ("model_data", models.JSONField(default=dict, verbose_name="模型数据")),
                (
                    "physics_data",
                    models.JSONField(default=dict, verbose_name="物理数据"),
                ),
                (
                    "interaction_data",
                    models.JSONField(default=dict, verbose_name="交互数据"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="objects/thumbnails/",
                        verbose_name="缩略图",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="公开物品"),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(default=0, verbose_name="下载次数"),
                ),
                (
                    "rating",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="评分",
                    ),
                ),
            ],
            options={
                "verbose_name": "虚拟物品",
                "verbose_name_plural": "虚拟物品",
                "db_table": "metaverse_objects",
                "ordering": ["-rating", "-download_count"],
            },
        ),
        migrations.CreateModel(
            name="VirtualWorld",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="激活状态"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="世界名称")),
                ("description", models.TextField(verbose_name="世界描述")),
                (
                    "world_type",
                    models.CharField(
                        choices=[
                            ("public", "公共世界"),
                            ("private", "私人世界"),
                            ("group", "群组世界"),
                            ("event", "活动世界"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="世界类型",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="worlds/thumbnails/",
                        verbose_name="缩略图",
                    ),
                ),
                ("scene_data", models.JSONField(default=dict, verbose_name="场景数据")),
                (
                    "max_capacity",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                        verbose_name="最大容量",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("inactive", "非活跃"),
                            ("maintenance", "维护中"),
                            ("archived", "已归档"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "visit_count",
                    models.PositiveIntegerField(default=0, verbose_name="访问次数"),
                ),
                ("settings", models.JSONField(default=dict, verbose_name="世界设置")),
            ],
            options={
                "verbose_name": "虚拟世界",
                "verbose_name_plural": "虚拟世界",
                "db_table": "metaverse_worlds",
                "ordering": ["-visit_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorldObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="激活状态"),
                ),
                ("position", models.JSONField(default=dict, verbose_name="位置信息")),
                ("rotation", models.JSONField(default=dict, verbose_name="旋转信息")),
                ("scale", models.JSONField(default=dict, verbose_name="缩放信息")),
                (
                    "properties",
                    models.JSONField(default=dict, verbose_name="自定义属性"),
                ),
            ],
            options={
                "verbose_name": "世界物品实例",
                "verbose_name_plural": "世界物品实例",
                "db_table": "metaverse_world_objects",
                "ordering": ["world", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorldPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="激活状态"),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[("view", "查看"), ("edit", "编辑"), ("admin", "管理")],
                        max_length=20,
                        verbose_name="权限类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "世界权限",
                "verbose_name_plural": "世界权限",
                "db_table": "metaverse_world_permissions",
            },
        ),
    ]
