# Generated by Django 5.2.1 on 2025-05-29 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("metaverse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="avatar",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avatars",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="组织者",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="core.tag", verbose_name="标签"
            ),
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="metaverse.event",
                verbose_name="活动",
            ),
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                through="metaverse.EventParticipant",
                to=settings.AUTH_USER_MODEL,
                verbose_name="参与者",
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="avatar",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="metaverse.avatar",
                verbose_name="使用的形象",
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metaverse_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="virtualobject",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_objects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="virtualobject",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="core.tag", verbose_name="标签"
            ),
        ),
        migrations.AddField(
            model_name="virtualworld",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_worlds",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="virtualworld",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="core.tag", verbose_name="标签"
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_sessions",
                to="metaverse.virtualworld",
                verbose_name="虚拟世界",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="metaverse.virtualworld",
                verbose_name="举办世界",
            ),
        ),
        migrations.AddField(
            model_name="worldobject",
            name="placed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="放置者",
            ),
        ),
        migrations.AddField(
            model_name="worldobject",
            name="virtual_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="metaverse.virtualobject",
                verbose_name="虚拟物品",
            ),
        ),
        migrations.AddField(
            model_name="worldobject",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="world_objects",
                to="metaverse.virtualworld",
                verbose_name="虚拟世界",
            ),
        ),
        migrations.AddField(
            model_name="worldpermission",
            name="granted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="granted_permissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="授权者",
            ),
        ),
        migrations.AddField(
            model_name="worldpermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="worldpermission",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="metaverse.virtualworld",
                verbose_name="虚拟世界",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventparticipant",
            unique_together={("event", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="worldpermission",
            unique_together={("world", "user", "permission_type")},
        ),
    ]
